services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - front

  front:
    build: ./frontend
    environment:
      # Diz ao React para fazer requisições API na mesma porta do site
      - VITE_URL_API=/api 
    # Opcional: watch para desenvolvimento (Hot Reloading)
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./backend
    container_name: devops_api
    restart: always
    ports:
      - "2375:2375"
    environment:
      - DB_HOST=db
      - DB_USER=admulisses       
      - DB_PASSWORD=ulisses123   
      - DB_NAME=devops_db
      - DB_PORT=5432             
      - PORT=2375
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:17-alpine
    container_name: devops_postgres
    restart: always
    environment:
      POSTGRES_USER: admulisses
      POSTGRES_PASSWORD: ulisses123
      POSTGRES_DB: devops_db
    ports:
      - "5433:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: