services:
  db:
    image: postgres:17-alpine
    container_name: devops_postgres
    restart: always
    environment:
      POSTGRES_USER: admulisses
      POSTGRES_PASSWORD: ulisses123
      POSTGRES_DB: devops_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: devops_api
    restart: always
    ports:
      - "2375:2375"
    environment:
      - API_EXTERNA=http://nginx/fakestore/products
      - API_EXTERNA_ID=https://nginx/fakestore/products/${id}
      - DB_HOST=db
      - DB_USER=admulisses       
      - DB_PASSWORD=ulisses123   
      - DB_NAME=devops_db
      - DB_PORT=5432             
      - PORT=2375
    depends_on:
      - db

volumes:
  postgres_data: