events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Rota para o Frontend (React)
        location / {
            proxy_pass http://front:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 2. Rota para o Backend local (Node.js)
        location /api/ {
            proxy_pass http://api:2375/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Rota API externa: Proxy Reverso para a FakeStoreAPI
        location /fakestore/ {
            proxy_pass https://fakestoreapi.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host fakestoreapi.com;
            proxy_set_header X-Real-IP $remote_addr;
            
            # libera o cors para caso o front precise
            add_header 'Access-Control-Allow-Origin' '*';
        }
    }
}