events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            return 200 "nginx rodando";
        }
        # Rota para a FakeStore
        location /fakestore/ {
            proxy_pass https://fakestoreapi.com/;
            proxy_ssl_server_name on;
            proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
            proxy_set_header Host fakestoreapi.com;
            proxy_set_header X-Real-IP $remote_addr;
            
            add_header 'Access-Control-Allow-Origin' '*';
        }
    }
}