events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        # 1. Roteia para o fonrend
        # O Vite roda na porta "5173"
        location / {
            proxy_pass http://front:5173; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        # 2. Roteia para o backend
        # Aponta para o serviço "api" na porta "2375"
        location /api/ {
            proxy_pass http://api:2375/; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # 3. Rota para a API externa
        location /fakestore/ {
            proxy_pass https://fakestoreapi.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host fakestoreapi.com;
            proxy_set_header X-Real-IP $remote_addr;
            
            add_header 'Access-Control-Allow-Origin' '*';
        }
    }
}
